-- Create members table with proper UUID support and sample data
CREATE TABLE IF NOT EXISTS members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  member_company TEXT,
  designation TEXT,
  about_me TEXT,
  profile_image_url TEXT,
  location TEXT,
  member_since DATE DEFAULT CURRENT_DATE,
  industry TEXT,
  membership_level TEXT,
  knowledgeable_about TEXT[],
  committee_tags TEXT[],
  interested_in_projects BOOLEAN DEFAULT false,
  is_favorite BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert sample data
INSERT INTO members (
  name, 
  email, 
  member_company, 
  designation, 
  about_me, 
  profile_image_url,
  location,
  industry,
  membership_level,
  knowledgeable_about, 
  committee_tags, 
  interested_in_projects,
  is_favorite
) VALUES 
(
  'Aaron Prather',
  'aaron.prather@astm.org',
  'ASTM',
  'Director, Robotics & Autonomous Systems',
  'Experienced robotics engineer with expertise in autonomous systems and manufacturing automation.',
  '/images/members/aaron-prather.jpeg',
  'Pittsburgh, PA',
  'Technology',
  'Premium',
  ARRAY['Automation', 'Autonomous Vehicles'],
  ARRAY['TAC Committee Member'],
  true,
  false
),
(
  'Aaron Williams',
  'aaron.williams@haptx.com',
  'HaptX',
  NULL,
  'Haptic technology specialist focused on tactile feedback systems.',
  NULL,
  'Seattle, WA',
  'Technology',
  'Standard',
  ARRAY['Classroom Training', 'VR/AR'],
  ARRAY[],
  false,
  false
),
(
  'Adam Newberry',
  'adam.newberry@ontheroad.com',
  'On the Road Companies',
  NULL,
  'Transportation and logistics expert with focus on autonomous vehicle deployment.',
  NULL,
  'Austin, TX',
  'Automotive',
  'Standard',
  ARRAY['Curricula Development'],
  ARRAY[],
  true,
  false
),
(
  'Amir Barati Farimani',
  'amir.farimani@cmu.edu',
  'Carnegie Mellon University',
  NULL,
  'Professor of Mechanical Engineering specializing in AI and robotics research.',
  NULL,
  'Pittsburgh, PA',
  'Education',
  'Premium',
  ARRAY['AI', 'Automation'],
  ARRAY['TAC Committee Member'],
  true,
  false
),
(
  'John Smith',
  'john.smith@astm.org',
  'ASTM',
  'Director, Robotics & Autonomous Systems',
  'Standards development expert with focus on robotics and automation.',
  NULL,
  'West Conshohocken, PA',
  'Technology',
  'Premium',
  ARRAY['Automation', 'Autonomous Vehicles'],
  ARRAY['TAC Committee Member'],
  false,
  false
),
(
  'Abdullah Alturki',
  'abdullah.alturki@pitt.edu',
  'University of Pittsburgh',
  NULL,
  'Graduate student researching autonomous systems and machine learning.',
  NULL,
  'Pittsburgh, PA',
  'Education',
  'Student',
  ARRAY[],
  ARRAY[],
  true,
  false
);
